### ISSUE TITLE
home button (Back Icon in Toolbar) in eventdetails not working properly 

### ISSUE THREAD

**Issue by TejasBhitle** [TejasBhitle/Matrix2017#9]
On pressing,  MainActivity starts with 'MEGA'  Tab opened irrespective whether the eventdetails was opened from a different tab or from the Favorites Fragment.

**Comment by psyclone20** [comment]
Fixed here:
https://github.com/TejasBhitle/Matrix2017/commit/c2e8a43ae97f5d0cf6fdedb0b37bcfcff4192de0
